The ``7-base_geometry`` module
======================
Using ``BaseGeometry``
-------------------

Importing the function from the module:
        >>> Bg = __import__("7-base_geometry").BaseGeometry

Checking for module docstring:
         >>> x = __import__("7-base_geometry").__doc__
         >>> len(x) > 1
         True

Checking for class docstring:
         >>> y = __import__("7-base_geometry").BaseGeometry.__doc__
         >>> len(y) > 1
         True

Checking for method docstring:
	 >>> m = __import__("7-base_geometry").BaseGeometry.area.__doc__
	 >>> len(m) > 1
	 True
	 >>> m2 = __import__("7-base_geometry").BaseGeometry.integer_validator.__doc__
         >>> len(m2) > 1
         True

Checking for area failure:
	 >>> a = Bg()
	 >>> a.area()
	 Traceback (most recent call last):
	 ...
	 Exception: area() is not implemented

Checking too many arguments for area:
	 >>> a.area(1)
	 Traceback (most recent call last):
         ...
	 TypeError: area() takes 1 positional argument but 2 were given

Checking integer validator for passing integer:
	 >>> a.integer_validator("integer", 1)

Checking for integer < 0;
	 >>> a.integer_validator("integer", -20)
	 Traceback (most recent call last):
         ...
         ValueError: integer must be greater than 0

Checking for integer == 0:
	 >>> a.integer_validator("integer", 0)
	 Traceback (most recent call last):
         ...
         ValueError: integer must be greater than 0

Checking for non-integer types:
	 >>> a.integer_validator("bool", True)
	 Traceback (most recent call last):
         ...
         TypeError: bool must be an integer
	 >>> a.integer_validator("float", 3.56)
         Traceback (most recent call last):
         ...
         TypeError: float must be an integer
	 >>> a.integer_validator("complex", complex(1, 1))
         Traceback (most recent call last):
         ...
         TypeError: complex must be an integer
	 >>> a.integer_validator("hello", "world")
         Traceback (most recent call last):
         ...
         TypeError: string must be an integer
	 >>> a.integer_validator("tuple", (4, 8))
         Traceback (most recent call last):
         ...
         TypeError: tuple must be an integer
	 >>> a.integer_validator("list", [3, 2, 1])
	 Traceback (most recent call last):
         ...
         TypeError: list must be an integer
	 >>> a.integer_validator("dict", {"key": "value"})
         Traceback (most recent call last):
         ...
         TypeError: dict must be an integer
	 >>> a.integer_validator("dic", {"john", "doe"})
         Traceback (most recent call last):
         ...
         TypeError: set must be an integer
	 >>> a.integer_validator("frozenset", frozenset(["hello", "world"]))
         Traceback (most recent call last):
         ...
         TypeError: frozenset must be an integer
	 >>> a.integer_validator("byte", b"bytes")
         Traceback (most recent call last):
         ...
         TypeError: bytes must be an integer
	 >>> a.integer_validator("bytearrays", bytearray(b"bytes"))
         Traceback (most recent call last):
         ...
         TypeError: bytearrays must be an integer

Checking for no arguments to integer_validator:
	 >>> a.integer_validator()
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Checking for too many arguments:
	 >>> a.integer_validator("integer", 4, 6)
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() takes 3 positional arguments but 4 were given

Checking for only 1 argument to integer_validator:
	 >>> a.integer_validator("integer")
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() missing 1 required positional argument: 'value'
